export const CHAMBER_INACTIVITY_TIMEOUT_MS = 60_000;
export const CHAMBER_PRESENCE_POLL_INTERVAL_MS = 10_000;
export const TYPING_INDICATOR_INITIAL_DELAY_MS = 700;
export const TYPING_INDICATOR_STAGGER_MS = 220;
